apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: minio:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-verifyssl: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: admin123